language: python
python:
  - 3.7
sudo: false
cache: "pip"
install:
  - "pip install -r requirements.txt"
script:
  - "tox -p all"
after_success:
  - "coverage erase"
  - "coverage combine"
  - "coveralls"
