language: python
python:
  - 3.5
services:
  - "mongodb"
sudo: false
cache: "pip"
install:
  - "pip install -r requirements.txt"
script:
  - "flake8 omm tests"
  - "radon cc -nc omm tests"
  - "tox"
after_success:
  - "coverage erase"
  - "coverage combine python27.coverage python35.coverage"
  - "coveralls"
